default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: <%= ENV['DB_SOCKET'] %>

development:
  <<: *default
  database: real_estate_development

test:
  <<: *default
  database: real_estate_test

production:
  <<: *default
  database: real_estate_production
